name: flutter_application_1
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages
 # Replace with the latest stable version
  
  # FontAwesome Icons package
  font_awesome_flutter: ^10.0.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.16.0
  pinput: ^5.0.0
  
  
  firebase_auth_web: ^5.8.13

  # Carousel Slider package
  carousel_slider: ^4.2.1 # Replace with the latest stable version if available

  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Lints for encouraging good coding practices
  flutter_lints: ^4.0.0

flutter:
  # Material icons for easy access to built-in Flutter icons
  uses-material-design: true

  # Asset configuration
  assets:
    - assets/ # Ensure you have assets in this folder

  # Example for adding custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro-Bold.ttf
  #         weight: 700
